### ISSUE TITLE
Shuffling input data without warning

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_deeplearning#1]
In Lasagne, why is all the data automatically shuffled in each minibatch for each epoch [in this code](https://github.com/nengo/nengo_deeplearning/blob/master/nengo_deeplearning/builder.py#L148)? If the user wants their data shuffled before training, shouldn't they specify it?

**Comment by drasmuss** [comment]
Yes we can add a flag to turn that on or off if you'd like.  Although I can't really think of any occasions when I would not want my data shuffled.

**Comment by drasmuss** [comment]
There is a flag for this in the new version of nengo_dl
